/* soapClient.cpp
   Generated by gSOAP 2.8.4 from WandaMsg.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#include "stdafx.h"
SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.4 2015-11-16 07:17:10 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetRTXInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetRTXInfo *ns1__SetRTXInfo, _ns1__SetRTXInfoResponse *ns1__SetRTXInfoResponse)
{	struct __ns1__SetRTXInfo soap_tmp___ns1__SetRTXInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetRTXInfo";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetRTXInfo.ns1__SetRTXInfo = ns1__SetRTXInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetRTXInfo(soap, &soap_tmp___ns1__SetRTXInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetRTXInfo(soap, &soap_tmp___ns1__SetRTXInfo, "-ns1:SetRTXInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetRTXInfo(soap, &soap_tmp___ns1__SetRTXInfo, "-ns1:SetRTXInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetRTXInfoResponse)
		return soap_closesock(soap);
	ns1__SetRTXInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetRTXInfoResponse->soap_get(soap, "ns1:SetRTXInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetSMSInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetSMSInfo *ns1__SetSMSInfo, _ns1__SetSMSInfoResponse *ns1__SetSMSInfoResponse)
{	struct __ns1__SetSMSInfo soap_tmp___ns1__SetSMSInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetSMSInfo";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetSMSInfo.ns1__SetSMSInfo = ns1__SetSMSInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetSMSInfo(soap, &soap_tmp___ns1__SetSMSInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetSMSInfo(soap, &soap_tmp___ns1__SetSMSInfo, "-ns1:SetSMSInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetSMSInfo(soap, &soap_tmp___ns1__SetSMSInfo, "-ns1:SetSMSInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetSMSInfoResponse)
		return soap_closesock(soap);
	ns1__SetSMSInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetSMSInfoResponse->soap_get(soap, "ns1:SetSMSInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetEmailInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetEmailInfo *ns1__SetEmailInfo, _ns1__SetEmailInfoResponse *ns1__SetEmailInfoResponse)
{	struct __ns1__SetEmailInfo soap_tmp___ns1__SetEmailInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetEmailInfo";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetEmailInfo.ns1__SetEmailInfo = ns1__SetEmailInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetEmailInfo(soap, &soap_tmp___ns1__SetEmailInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetEmailInfo(soap, &soap_tmp___ns1__SetEmailInfo, "-ns1:SetEmailInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetEmailInfo(soap, &soap_tmp___ns1__SetEmailInfo, "-ns1:SetEmailInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetEmailInfoResponse)
		return soap_closesock(soap);
	ns1__SetEmailInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetEmailInfoResponse->soap_get(soap, "ns1:SetEmailInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetMMSInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetMMSInfo *ns1__SetMMSInfo, _ns1__SetMMSInfoResponse *ns1__SetMMSInfoResponse)
{	struct __ns1__SetMMSInfo soap_tmp___ns1__SetMMSInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetMMSInfo";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetMMSInfo.ns1__SetMMSInfo = ns1__SetMMSInfo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetMMSInfo(soap, &soap_tmp___ns1__SetMMSInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetMMSInfo(soap, &soap_tmp___ns1__SetMMSInfo, "-ns1:SetMMSInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetMMSInfo(soap, &soap_tmp___ns1__SetMMSInfo, "-ns1:SetMMSInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetMMSInfoResponse)
		return soap_closesock(soap);
	ns1__SetMMSInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetMMSInfoResponse->soap_get(soap, "ns1:SetMMSInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetRTXNotify(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetRTXNotify *ns1__SetRTXNotify, _ns1__SetRTXNotifyResponse *ns1__SetRTXNotifyResponse)
{	struct __ns1__SetRTXNotify soap_tmp___ns1__SetRTXNotify;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetRTXNotify";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetRTXNotify.ns1__SetRTXNotify = ns1__SetRTXNotify;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetRTXNotify(soap, &soap_tmp___ns1__SetRTXNotify);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetRTXNotify(soap, &soap_tmp___ns1__SetRTXNotify, "-ns1:SetRTXNotify", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetRTXNotify(soap, &soap_tmp___ns1__SetRTXNotify, "-ns1:SetRTXNotify", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetRTXNotifyResponse)
		return soap_closesock(soap);
	ns1__SetRTXNotifyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetRTXNotifyResponse->soap_get(soap, "ns1:SetRTXNotifyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetRTXJSON(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetRTXJSON *ns1__SetRTXJSON, _ns1__SetRTXJSONResponse *ns1__SetRTXJSONResponse)
{	struct __ns1__SetRTXJSON soap_tmp___ns1__SetRTXJSON;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetRTXJSON";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetRTXJSON.ns1__SetRTXJSON = ns1__SetRTXJSON;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetRTXJSON(soap, &soap_tmp___ns1__SetRTXJSON);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetRTXJSON(soap, &soap_tmp___ns1__SetRTXJSON, "-ns1:SetRTXJSON", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetRTXJSON(soap, &soap_tmp___ns1__SetRTXJSON, "-ns1:SetRTXJSON", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetRTXJSONResponse)
		return soap_closesock(soap);
	ns1__SetRTXJSONResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetRTXJSONResponse->soap_get(soap, "ns1:SetRTXJSONResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetSMSJSON(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetSMSJSON *ns1__SetSMSJSON, _ns1__SetSMSJSONResponse *ns1__SetSMSJSONResponse)
{	struct __ns1__SetSMSJSON soap_tmp___ns1__SetSMSJSON;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetSMSJSON";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetSMSJSON.ns1__SetSMSJSON = ns1__SetSMSJSON;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetSMSJSON(soap, &soap_tmp___ns1__SetSMSJSON);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetSMSJSON(soap, &soap_tmp___ns1__SetSMSJSON, "-ns1:SetSMSJSON", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetSMSJSON(soap, &soap_tmp___ns1__SetSMSJSON, "-ns1:SetSMSJSON", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetSMSJSONResponse)
		return soap_closesock(soap);
	ns1__SetSMSJSONResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetSMSJSONResponse->soap_get(soap, "ns1:SetSMSJSONResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetEmailJSON(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetEmailJSON *ns1__SetEmailJSON, _ns1__SetEmailJSONResponse *ns1__SetEmailJSONResponse)
{	struct __ns1__SetEmailJSON soap_tmp___ns1__SetEmailJSON;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetEmailJSON";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetEmailJSON.ns1__SetEmailJSON = ns1__SetEmailJSON;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetEmailJSON(soap, &soap_tmp___ns1__SetEmailJSON);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetEmailJSON(soap, &soap_tmp___ns1__SetEmailJSON, "-ns1:SetEmailJSON", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetEmailJSON(soap, &soap_tmp___ns1__SetEmailJSON, "-ns1:SetEmailJSON", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetEmailJSONResponse)
		return soap_closesock(soap);
	ns1__SetEmailJSONResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetEmailJSONResponse->soap_get(soap, "ns1:SetEmailJSONResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetSMSInfoC(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetSMSInfoC *ns1__SetSMSInfoC, _ns1__SetSMSInfoCResponse *ns1__SetSMSInfoCResponse)
{	struct __ns1__SetSMSInfoC soap_tmp___ns1__SetSMSInfoC;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetSMSInfoC";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetSMSInfoC.ns1__SetSMSInfoC = ns1__SetSMSInfoC;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetSMSInfoC(soap, &soap_tmp___ns1__SetSMSInfoC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetSMSInfoC(soap, &soap_tmp___ns1__SetSMSInfoC, "-ns1:SetSMSInfoC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetSMSInfoC(soap, &soap_tmp___ns1__SetSMSInfoC, "-ns1:SetSMSInfoC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetSMSInfoCResponse)
		return soap_closesock(soap);
	ns1__SetSMSInfoCResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetSMSInfoCResponse->soap_get(soap, "ns1:SetSMSInfoCResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetRTXInfoC(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetRTXInfoC *ns1__SetRTXInfoC, _ns1__SetRTXInfoCResponse *ns1__SetRTXInfoCResponse)
{	struct __ns1__SetRTXInfoC soap_tmp___ns1__SetRTXInfoC;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetRTXInfoC";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetRTXInfoC.ns1__SetRTXInfoC = ns1__SetRTXInfoC;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetRTXInfoC(soap, &soap_tmp___ns1__SetRTXInfoC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetRTXInfoC(soap, &soap_tmp___ns1__SetRTXInfoC, "-ns1:SetRTXInfoC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetRTXInfoC(soap, &soap_tmp___ns1__SetRTXInfoC, "-ns1:SetRTXInfoC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetRTXInfoCResponse)
		return soap_closesock(soap);
	ns1__SetRTXInfoCResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetRTXInfoCResponse->soap_get(soap, "ns1:SetRTXInfoCResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetEmailInfoC(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetEmailInfoC *ns1__SetEmailInfoC, _ns1__SetEmailInfoCResponse *ns1__SetEmailInfoCResponse)
{	struct __ns1__SetEmailInfoC soap_tmp___ns1__SetEmailInfoC;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetEmailInfoC";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetEmailInfoC.ns1__SetEmailInfoC = ns1__SetEmailInfoC;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetEmailInfoC(soap, &soap_tmp___ns1__SetEmailInfoC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetEmailInfoC(soap, &soap_tmp___ns1__SetEmailInfoC, "-ns1:SetEmailInfoC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetEmailInfoC(soap, &soap_tmp___ns1__SetEmailInfoC, "-ns1:SetEmailInfoC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetEmailInfoCResponse)
		return soap_closesock(soap);
	ns1__SetEmailInfoCResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetEmailInfoCResponse->soap_get(soap, "ns1:SetEmailInfoCResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetMMSInfoC(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetMMSInfoC *ns1__SetMMSInfoC, _ns1__SetMMSInfoCResponse *ns1__SetMMSInfoCResponse)
{	struct __ns1__SetMMSInfoC soap_tmp___ns1__SetMMSInfoC;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetMMSInfoC";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetMMSInfoC.ns1__SetMMSInfoC = ns1__SetMMSInfoC;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetMMSInfoC(soap, &soap_tmp___ns1__SetMMSInfoC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetMMSInfoC(soap, &soap_tmp___ns1__SetMMSInfoC, "-ns1:SetMMSInfoC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetMMSInfoC(soap, &soap_tmp___ns1__SetMMSInfoC, "-ns1:SetMMSInfoC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetMMSInfoCResponse)
		return soap_closesock(soap);
	ns1__SetMMSInfoCResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetMMSInfoCResponse->soap_get(soap, "ns1:SetMMSInfoCResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetRTXNotifyC(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetRTXNotifyC *ns1__SetRTXNotifyC, _ns1__SetRTXNotifyCResponse *ns1__SetRTXNotifyCResponse)
{	struct __ns1__SetRTXNotifyC soap_tmp___ns1__SetRTXNotifyC;
	if (!soap_endpoint)
		soap_endpoint = "http://10.199.82.184:10001/WandaMsgService.svc";
	if (!soap_action)
		soap_action = "http://tempuri.org/IWandaMsg/SetRTXNotifyC";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetRTXNotifyC.ns1__SetRTXNotifyC = ns1__SetRTXNotifyC;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetRTXNotifyC(soap, &soap_tmp___ns1__SetRTXNotifyC);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetRTXNotifyC(soap, &soap_tmp___ns1__SetRTXNotifyC, "-ns1:SetRTXNotifyC", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetRTXNotifyC(soap, &soap_tmp___ns1__SetRTXNotifyC, "-ns1:SetRTXNotifyC", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetRTXNotifyCResponse)
		return soap_closesock(soap);
	ns1__SetRTXNotifyCResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetRTXNotifyCResponse->soap_get(soap, "ns1:SetRTXNotifyCResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
